#!/usr/bin/env python3
from pathlib import Path
import struct
import sys

root = Path(__file__).resolve().parents[2]
src_dir = root / 'docs' / 'diagrams' / 'mermaid' / 'src'
png_dir = root / 'docs' / 'diagrams' / 'mermaid' / 'png'
docs_png_fallback = root / 'docs' / 'diagrams'

errors = []

for mmd in sorted(src_dir.glob('*.mmd')):
    png = png_dir / (mmd.stem + '.png')
    if not png.exists():
        # Try docs/diagrams with _diagram_ prefix (generated by extract_diagrams.js)
        alt = docs_png_fallback / (mmd.stem.rsplit('_', 1)[0] + '_diagram_' + mmd.stem.rsplit('_', 1)[-1] + '.png')
        if alt.exists():
            png = alt
        else:
            # Try any PNG in docs/diagrams whose stem contains this source's stem
            candidates = [p for p in docs_png_fallback.glob('*.png') if mmd.stem in p.stem]
            if candidates:
                png = candidates[0]
            else:
                errors.append(f"Missing PNG for {mmd.relative_to(root)} -> {png.relative_to(root)}")
                continue

    if not png.exists():
        continue

    with png.open('rb') as f:
        sig = f.read(8)
        if sig != b'\x89PNG\r\n\x1a\n':
            errors.append(f"Invalid PNG signature: {png.relative_to(root)}")
            continue
        chunk_len = struct.unpack('>I', f.read(4))[0]
        chunk_type = f.read(4)
        if chunk_type != b'IHDR' or chunk_len < 13:
            errors.append(f"Invalid IHDR chunk: {png.relative_to(root)}")
            continue
        width, height = struct.unpack('>II', f.read(8))
        if width < 300 or height < 150:
            errors.append(f"Low resolution PNG ({width}x{height}): {png.relative_to(root)}")

if errors:
    print('Diagram asset verification failed:')
    for err in errors:
        print(' -', err)
    sys.exit(2)

print(f"Diagram assets verified: {len(list(src_dir.glob('*.mmd')))} sources with valid PNG outputs.")
