classDiagram
    direction LR
    class FileConfigProvider {
        -Properties properties
        +FileConfigProvider()
        +loadConfiguration() void
        +getStringProperty(final String key, final String defaultValue) String
        +getIntProperty(final String key, final int defaultValue) int
        +getBooleanProperty(final String key, final boolean defaultValue) boolean
        +hasProperty(final String key) boolean
    }

    FileConfigProvider ..|> IConfigProvider
    class IConfigProvider {
        <<interface>>
    }

