flowchart TB
    subgraph Entry["Entry Layer"]
        Main["Main<br/>Application Entry Point"]
    end
    
    subgraph Config["Config Layer com.splendor.config"]
        IConfigProvider["IConfigProvider<br/>Config Interface"]
        FileConfigProvider["FileConfigProvider<br/>File Config Implementation"]
        ConfigKeys["ConfigKeys<br/>Config Key Constants"]
        ConfigException["ConfigException<br/>Config Exception"]
    end
    
    subgraph Controller["Controller Layer com.splendor.controller"]
        GameController["GameController<br/>Main Game Controller"]
        TurnController["TurnController<br/>Turn Controller"]
        PlayerController["PlayerController<br/>Player Controller"]
        MenuBuilder["MenuBuilder<br/>Menu Builder"]
        MenuAction["MenuAction<br/>Menu Action Enum"]
        MenuOption["MenuOption<br/>Menu Option"]
    end
    
    subgraph Model["Model Layer com.splendor.model"]
        Game["Game<br/>Game State Model"]
        Board["Board<br/>Game Board"]
        Player["Player<br/>Player"]
        ComputerPlayer["ComputerPlayer<br/>AI Player"]
        Card["Card<br/>Development Card"]
        Noble["Noble<br/>Noble Card"]
        Gem["Gem<br/>Gem Enum"]
        Move["Move<br/>Player Action"]
        MoveType["MoveType<br/>Action Type Enum"]
        GameState["GameState<br/>Game State"]
    end
    
    subgraph Validator["Validator Layer com.splendor.model.validator"]
        MoveValidator["MoveValidator<br/>Move Validator"]
        GameRuleValidator["GameRuleValidator<br/>Game Rule Validator"]
        ValidationResult["ValidationResult<br/>Validation Result"]
    end
    
    subgraph View["View Layer com.splendor.view"]
        IGameView["IGameView<br/>View Interface"]
        ConsoleView["ConsoleView<br/>Console View"]
        RemoteView["RemoteView<br/>Remote View"]
        NetworkGameView["NetworkGameView<br/>Network Game View"]
        Colors["Colors<br/>ANSI Color Utils"]
        CardRenderer["CardRenderer<br/>Card Renderer"]
        GameRenderer["GameRenderer<br/>Game Renderer"]
        NetworkMessageHandler["NetworkMessageHandler<br/>Network Message Handler"]
    end
    
    subgraph Network["Network Layer com.splendor.network"]
        ServerSocketHandler["ServerSocketHandler<br/>Server Socket Handler"]
        ClientHandler["ClientHandler<br/>Client Handler"]
        NetworkException["NetworkException<br/>Network Exception"]
    end
    
    subgraph Data["Data Layer com.splendor.data"]
        CardDataProvider["CardDataProvider<br/>Card Data Interface"]
        CardLoader["CardLoader<br/>Card Loader"]
        CsvCardParser["CsvCardParser<br/>CSV Parser"]
        CustomCardDeckProvider["CustomCardDeckProvider<br/>Custom Deck Provider"]
        DataLoadException["DataLoadException<br/>Data Load Exception"]
    end
    
    subgraph Util["Utility Layer com.splendor.util"]
        AnsiUtils["AnsiUtils<br/>ANSI Utils"]
        Constants["Constants<br/>App Constants"]
        GameLogger["GameLogger<br/>Game Logger"]
        GemParser["GemParser<br/>Gem Parser"]
        InputResolver["InputResolver<br/>Input Resolver"]
        MoveFormatter["MoveFormatter<br/>Move Formatter"]
    end
    
    subgraph Exception["Exception Layer com.splendor.exception"]
        SplendorException["SplendorException<br/>Base Exception"]
        GameStateException["GameStateException<br/>Game State Exception"]
        InsufficientTokensException["InsufficientTokensException<br/>Insufficient Tokens Exception"]
        InvalidMoveException["InvalidMoveException<br/>Invalid Move Exception"]
        InvalidPlayerActionException["InvalidPlayerActionException<br/>Invalid Player Action Exception"]
    end
    
    Main --> GameController
    GameController --> Game
    GameController --> IGameView
    GameController --> IConfigProvider
    GameController --> MoveValidator
    GameController --> GameRuleValidator
    
    IConfigProvider <|.. FileConfigProvider
    IGameView <|.. ConsoleView
    IGameView <|.. RemoteView
    IGameView <|.. NetworkGameView
    
    CardDataProvider <|.. CsvCardParser
    CardDataProvider <|.. CustomCardDeckProvider
    CardLoader --> CardDataProvider
    
    Game --> Board
    Game --> Player
    Game --> GameState
    Board --> Card
    Board --> Noble
    Board --> Gem
    Player --> Card
    Player --> Noble
    Player --> Gem
    Move --> MoveType
    ComputerPlayer --|> Player
    
    GameRuleValidator --> GameState
    MoveValidator --> Move
    
    ServerSocketHandler --> NetworkMessageHandler
    ClientHandler --> NetworkMessageHandler
    
    GameStateException --|> SplendorException
    InsufficientTokensException --|> SplendorException
    InvalidMoveException --|> SplendorException
    InvalidPlayerActionException --|> SplendorException
    NetworkException --|> SplendorException
    ConfigException --|> Exception
    DataLoadException --|> Exception
