classDiagram
    direction LR
    class ConfigException {
        +ConfigException(final String message)
        +ConfigException(final String message, final Throwable cause)
    }

    ConfigException --|> Exception
    class DataLoadException {
        +DataLoadException(final String message)
        +DataLoadException(final String message, final Throwable cause)
    }

    DataLoadException --|> Exception
    class GameStateException {
        +GameStateException(final String message)
        +GameStateException(final String messageFormat, final Object... args)
    }

    GameStateException --|> SplendorException
    class InsufficientTokensException {
        +InsufficientTokensException(final String message)
        +InsufficientTokensException(final String messageFormat, final Object... args)
    }

    InsufficientTokensException --|> SplendorException
    class InvalidMoveException {
        +InvalidMoveException(final String message)
        +InvalidMoveException(final String messageFormat, final Object... args)
    }

    InvalidMoveException --|> SplendorException
    class InvalidPlayerActionException {
        +InvalidPlayerActionException(final String message)
        +InvalidPlayerActionException(final String messageFormat, final Object... args)
    }

    InvalidPlayerActionException --|> SplendorException
    class NetworkException {
        +NetworkException(final String message)
        +NetworkException(final String message, final Throwable cause)
    }

    NetworkException --|> SplendorException
    class SplendorException {
        +SplendorException(final String message)
        +SplendorException(final String messageFormat, final Object... args)
        +SplendorException(final String message, final Throwable cause)
    }

    SplendorException --|> Exception
