%%{init: {"theme": "default", "classDiagram": {"nodeSpacing": 20, "rankSpacing": 30}}}%%
classDiagram
  direction LR

  class CardLoader {
    +loadCards(tier int)$ List~Card~
    +loadNobles()$ List~Noble~
  }
  class CsvCardParser {
    +CsvCardParser(configProvider IConfigProvider)
    +loadCards(tier int) List~Card~
    +loadNobles() List~Noble~
  }

  CardLoader ..> CsvCardParser : delegates to
