%%{init: {"theme": "default"}}%%
classDiagram
  direction LR
  class IGameView { <<interface>> }
  class ConsoleView
  class NetworkGameView
  class RemoteView
  class GameRenderer
  class CardRenderer
  class Colors

  IGameView <|.. ConsoleView
  IGameView <|.. NetworkGameView
  IGameView <|.. RemoteView
  NetworkGameView *-- RemoteView
  ConsoleView --> GameRenderer
  RemoteView --> GameRenderer
  GameRenderer --> CardRenderer
