flowchart LR
    subgraph Domain[Domain Model]
        D[Game, Player, Board,<br/>Card, Noble, Move, Gem]
    end
    
    subgraph Controllers[Controllers]
        C[GameController,<br/>TurnController,<br/>PlayerController,<br/>MenuBuilder]
    end
    
    subgraph Validators[Validators]
        V[MoveValidator,<br/>GameRuleValidator]
    end
    
    subgraph Views[Views]
        VI[ConsoleView,<br/>RemoteView,<br/>GameRenderer]
    end
    
    subgraph Network[Network]
        N[ServerSocketHandler,<br/>ClientHandler]
    end
    
    subgraph Exceptions[Exceptions]
        E[SplendorException<br/>Hierarchy]
    end
    
    C --> D
    C --> V
    C --> VI
    VI --> C
    N --> VI
    C -.-> E
    V -.-> E
    N -.-> E